server:
  port: 8081

eureka:
  instance:
    #安全保护机制（端口）关闭
    secure-port-enabled: false
  client:
    #表示该eureka节点不能注册服务
    register-with-eureka: false
    #表示该eureka节点不能发现（订阅）服务
    fetch-registry: false
    service-url:
      #配置eureka服务器地址
      defaultZone: http://127.0.0.1:8081/eureka/

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
